spring.application.name=flowtrack
server.port=8080


# ============================================
# PRODUÇÃO / AIVEN POSTGRES (Não funciona na rede da UFRN)
# ============================================
# spring.datasource.url=jdbc:postgresql://pg-27647a12-ufrn.f.aivencloud.com:15406/defaultdb?sslmode=require&timezone=America/Sao_Paulo
# spring.datasource.username=avnadmin
# spring.datasource.password=AVNS_rR3V-ImWunBXqNlRPS0
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=120000


# ============================================
# AMBIENTE LOCAL (Caso esteja na rede da UFRN)
# (Descomente essas linhas quando quiser usar o banco local)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/flowtrack?timezone=America/Sao_Paulo
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================
# Configurações gerais
# ============================================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# Configurações Flyway
# ============================================
spring.flyway.encoding=UTF-8
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ============================================
# Configurações de Timezone
# ============================================
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo