spring.application.name=flowtrack
server.port=8080


# ============================================
# PRODUÇÃO / AIVEN POSTGRES (Não funciona na rede da UFRN)
# ============================================
spring.datasource.url=jdbc:postgresql://pg-27647a12-ufrn.f.aivencloud.com:15406/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_rR3V-ImWunBXqNlRPS0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=120000


# ============================================
# AMBIENTE LOCAL (Caso esteja na rede da UFRN)
# (Descomente essas linhas quando quiser usar o banco local)
# ============================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/flowtrack
# spring.datasource.username=postgres
# spring.datasource.password=admin123
# spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================
# Configurações gerais
# ============================================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE