# Bloco HTTP (Porta 80) - Redireciona tudo para HTTPS
server {
    listen 80;
    server_name flowtrack.kaioeduardo.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Bloco HTTPS (Porta 443)
server {
    listen 443 ssl;
    server_name flowtrack.kaioeduardo.com;

    # Certificados SSL (Montados via Docker Volume)
    ssl_certificate /etc/letsencrypt/live/flowtrack.kaioeduardo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flowtrack.kaioeduardo.com/privkey.pem;

    # Configurações de segurança SSL recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Frontend (Next.js)
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Backend (Spring Boot)
    location /api {
        proxy_pass http://backend:8080/api;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Avisa o Spring que a requisição original era HTTPS
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}